INSERT INTO books (title, author, release_year) VALUES
    ('The Lord of the Rings: The Fellowship of the Ring', 'J.R.R. Tolkien', 1954),
    ('The Lord of the Rings: The Two Towers', 'J.R.R. Tolkien', 1954),
    ('The Lord of the Rings: The Return of the King', 'J.R.R. Tolkien', 1955),
    ('The Hobbit', 'J.R.R. Tolkien', 1937),
    ('Harry Potter and the Sorcerer\'s Stone', 'J.K. Rowling', 1997),
    ('Harry Potter and the Chamber of Secrets', 'J.K. Rowling', 1998),
    ('Alice\'s Adventures in Wonderland', 'Lewis Carroll', 1865),
    ('Through the Looking-Glass', 'Lewis Carroll', 1871),
    ('The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'C.S. Lewis', 1950),
    ('The Chronicles of Narnia: Prince Caspian', 'C.S. Lewis', 1951),
    ('Peter Pan', 'J.M. Barrie', 1911),
    ('The Wizard of Oz', 'L. Frank Baum', 1900),
    ('Treasure Island', 'Robert Louis Stevenson', 1883),
    ('Journey to the Center of the Earth', 'Jules Verne', 1864),
    ('Around the World in Eighty Days', 'Jules Verne', 1872),
    ('The Little Prince', 'Antoine de Saint-Exupéry', 1943),
    ('Charlie and the Chocolate Factory', 'Roald Dahl', 1964),
    ('Matilda', 'Roald Dahl', 1988),
    ('Percy Jackson & The Olympians: The Lightning Thief', 'Rick Riordan', 2005),
    ('The Hunger Games', 'Suzanne Collins', 2008),
    ('The Great Gatsby', 'F. Scott Fitzgerald', 1925),
    ('The Great Gatsby', 'Graphic Novel Edition', 2021),
    ('1984', 'George Orwell', 1949),
    ('Animal Farm', 'George Orwell', 1945),
    ('Brave New World', 'Aldous Huxley', 1932),
    ('The Catcher in the Rye', 'J.D. Salinger', 1951),
    ('The Hobbit', 'Illustrated Version', 2010),
    ('Fahrenheit 451', 'Ray Bradbury', 1953),
    ('To Kill a Mockingbird', 'Harper Lee', 1960),
    ('Moby Dick', 'Herman Melville', 1851),
    ('The Shining', 'Stephen King', 1977),
    ('It', 'Stephen King', 1986),
    ('Dune', 'Frank Herbert', 1965),
    ('Neuromancer', 'William Gibson', 1984),
    ('Foundation', 'Isaac Asimov', 1951),
    ('Starship Troopers', 'Robert A. Heinlein', 1959),
    ('The Road', 'Cormac McCarthy', 2006),
    ('Project Hail Mary', 'Andy Weir', 2021),
    ('The Martian', 'Andy Weir', 2011);